version: '4.39.0'

services:
  postgres:
    container_name: rocketseat-api-course
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=rocketseat
      - POSTGRES_PASSWORD=r0ck3ts34t
      - POSTGRES_DB=rocketseat-api-course
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local